provider: java
build:
  steps:
    - name: Install Maven
      commands:
        - apt update
        - apt install -y maven
        - mvn -version
deploy:
  startCommand: mvn -f backend/pom.xml tomcat7:run